# The URL the site will be built for
base_url = "https://teo-orthlieb.github.io/"

title = "Teo Orthlieb"
description = "Teo Orthlieb's personal website"
default_language = "en"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "project", feed = true }]

[markdown.highlighting]
# Whether to do syntax highlighting
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here
